### ISSUE TITLE
Spectral Compressor crashing FL Studio while opening the gui inside Patcher

### ISSUE THREAD

**Issue by Wood3nLeaF** [robbert-vdh/nih-plug#122] opened 2024-03-05 18:17 UTC
i loaded up Spectral Compressor in FL STUDIO's patcher and tried to open up the gui then it crashed
i'm using Windows 10
![QQ截图20240306021442](https://github.com/robbert-vdh/nih-plug/assets/111210803/6aa47d55-970d-4c4f-9c93-86fb27635c33)

**Comment by robbert-vdh** [comment] 2024-03-10 19:53
There's something with certain versions of FL Studio and (presumably recent) changes to baseview's OpenGL handling. Closing as a duplicate of #125 (which is newer, but I already replied there :sweat_smile:).

**Closed by robbert-vdh** 2024-03-10 19:53 UTC
